config/routes.rb
PhoenixStr::Application.routes.draw do

  get "log_out" => "admin_session#destroy", :as => "log_out"
  get "log_in"  => "admin_session#new",     :as => "log_in"

  get "page/page1"
  get "page/page2"
  get "page/page3"
  get "page/page4"

  scope '(:locale)' do
   
    resources :admin_session
    resources :admined_page1s
    root to: 'page#page1', as: 'store'

  end

end

app/models/admined_login.rb
class AdminedLogin < ActiveRecord::Base

  def self.authenticate( name, password )
    user = find_by_name(name)
    if user &&
       user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/models/admined_page1.rb
class AdminedPage1 < ActiveRecord::Base
end

app/controllers/actor_admined_page_controller.rb
class ActorAdminedPageController < ApplicationController

  before_filter :get_admined_vars
  def get_admined_vars
    @title         = "Admin Page"
    @header_img    = "header_home.jpg"
    @wallpaper_img = "wallpaper_home.jpg"
    @bodyID        = "page1"

    @page1_tab_link = admined_page1s_path
    @page2_tab_link = admined_page1s_path
    @page3_tab_link = admined_page1s_path
    @page4_tab_link = admined_page1s_path
   end


  before_filter :require_login
 
  private
 
  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to log_in_path # halts request cycle
    end
  end
 
  # The logged_in? method simply returns true if the user is logged
  # in and false otherwise. It does this by "booleanizing" the
  # current_user method we created previously using a double ! operator.
  # Note that this is not common in Ruby and is discouraged unless you
  # really mean to convert something into true or false.
  def logged_in?
    !!current_user
  end

  private
 
  # Finds the User with the ID stored in the session with the key
  # :current_user_id This is a common way to handle user login in
  # a Rails application; logging in sets the session value and
  # logging out removes it.
  def current_user
    @_current_user ||= session[:current_user_id] &&
      AdminedLogin.find_by_id(session[:current_user_id])
  end

end

app/controllers/actor_viewed_page_controller.rb
class ActorViewedPageController < ApplicationController

  before_filter :get_viewed_page_vars
  def get_viewed_page_vars
    @page1_tab_link = page_page1_path
    @page2_tab_link = page_page2_path
    @page3_tab_link = page_page3_path
    @page4_tab_link = page_page4_path
  end

end

app/controllers/admin_session_controller.rb
class AdminSessionController < ApplicationController
  def new
  end

  before_filter :get_session_vars
  def get_session_vars
    @title         = "Session Page"
    @header_img    = "header_home.jpg"
    @wallpaper_img = "wallpaper_home.jpg"
    @bodyID        = "page1"
  end

  def create
    user = AdminedLogin.authenticate(params[:name], params[:password] )
    if user
      session[:current_user_id] = user.id
      redirect_to admined_page1s_path, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  # "Delete" a login, aka "log the user out"
  def destroy
    # Remove the user id from the session
    @_current_user = session[:current_user_id] = nil
    redirect_to page_page1_path
  end

end

app/controllers/admined_page1s_controller.rb
class AdminedPage1sController < ActorAdminedPageController
  # GET /admined_page1s
  # GET /admined_page1s.json
  def index
    @admined_page1s = AdminedPage1.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admined_page1s }
    end
  end

  # GET /admined_page1s/1
  # GET /admined_page1s/1.json
  def show
    @admined_page1 = AdminedPage1.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admined_page1 }
    end
  end

  # GET /admined_page1s/new
  # GET /admined_page1s/new.json
  def new
    @admined_page1 = AdminedPage1.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admined_page1 }
    end
  end

  # GET /admined_page1s/1/edit
  def edit
    @admined_page1 = AdminedPage1.find(params[:id])
  end

  # POST /admined_page1s
  # POST /admined_page1s.json
  def create
    @admined_page1 = AdminedPage1.new(params[:admined_page1])

    respond_to do |format|
      if @admined_page1.save
        format.html { redirect_to @admined_page1, notice: 'Admined page1 was successfully created.' }
        format.json { render json: @admined_page1, status: :created, location: @admined_page1 }
      else
        format.html { render action: "new" }
        format.json { render json: @admined_page1.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admined_page1s/1
  # PUT /admined_page1s/1.json
  def update
    @admined_page1 = AdminedPage1.find(params[:id])

    respond_to do |format|
      if @admined_page1.update_attributes(params[:admined_page1])
        format.html { redirect_to @admined_page1, notice: 'Admined page1 was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @admined_page1.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admined_page1s/1
  # DELETE /admined_page1s/1.json
  def destroy
    @admined_page1 = AdminedPage1.find(params[:id])
    @admined_page1.destroy

    respond_to do |format|
      format.html { redirect_to admined_page1s_url }
      format.json { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_i18n_locale_from_params
  before_filter :get_app_vars

  protected
  def get_app_vars
    @job_title_p1 = "Praxis fur Frauenheilkunde "
    @job_title_p2 = "Geburtshilfe"
    @full_name    = "Dr med. Forename Surename"
    @logo_img     = "logo.gif"
    @favicon_img  = "favicon.ico"
    @address      = "Add the address here"
    @phone_number = "Tel: +11 123 456 789"
    @fax_number   = "Fax: +22 123 456 789"
  end

  def set_i18n_locale_from_params
    if params[:locale]
      if I18n.available_locales.include?(params[:locale].to_sym)
        I18n.locale = params[:locale]
      else
        flash.now[:notice] = "#{params[:locale]} translation not available"
        logger.error flash.now[:notice]
      end
    end
  end

  def default_url_options
    { locale: I18n.locale }
  end

end

app/controllers/page_controller.rb
class PageController < ActorViewedPageController
  http_basic_authenticate_with :name => "phoenix", :password => "phoenix"
   
  before_filter :para1
  def para1
    @para1 = AdminedPage1.all
  end

  def page1
    if params[:set_locale]
      redirect_to store_path(locale: params[:set_locale])
    end

    @title         = "Home"
    @header_img    = "header_home.jpg"
    @wallpaper_img = "wallpaper_home.jpg"
    @bodyID        = "page1"
    @admined_page1s = AdminedPage1.all
  end

  def page2
    @title         = "Kurse"
    @header_img    = "header_kurse.jpg"
    @wallpaper_img = "wallpaper_kurse.jpg"
    @bodyID        = "page2"
    @welcome_img   = "welcome.gif"
    @signature_img = "kentenich_signature.gif"
  end

  def page3
    @title         = "Kentenich"
    @header_img    = "header_home.jpg"
    @wallpaper_img = "wallpaper_kentenich.jpg"
    @bodyID        = "page3"
  end

  def page4
    @title         = "Praxisteam"
    @header_img    = "header_praxisteam.jpg"
    @wallpaper_img = "wallpaper_praxisteam.jpg"
    @bodyID        = "page4"
  end

end

app/helpers/actor_admined_page_helper.rb
module ActorAdminedPageHelper
end

app/helpers/actor_viewed_page_helper.rb
module ActorViewedPageHelper
end

app/helpers/admin_session_helper.rb
module AdminSessionHelper
end

app/helpers/admined_page1s_helper.rb
module AdminedPage1sHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/admin_session/new.html.erb
<h1>Log in</h1>

<%= form_tag "admin_session#new" do %>

  <p>
    <%= label_tag :name %><br />
    <%= text_field_tag :name, params[:name] %>
  </p>
  <p>
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </p>
  <p class="button"><%= submit_tag "Log In" %></p>

<% end %>

app/views/admined_page1s/_form.html.erb
<%= form_for(@admined_page1) do |f| %>

  <div id="log_out_link_id">
    <%= link_to "Log out", log_out_path %>
  </div>

  <% if @admined_page1.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admined_page1.errors.count, "error") %> prohibited this admined_page1 from being saved:</h2>

      <ul>
      <% @admined_page1.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :p1 %><br />
    <%= f.text_area :p1 %>
  </div>
  <div class="field">
    <%= f.label :p2 %><br />
    <%= f.text_area :p2 %>
  </div>
  <div class="field">
    <%= f.label :p3 %><br />
    <%= f.text_area :p3 %>
  </div>
  <div class="field">
    <%= f.label :language %><br />
    <%= f.text_field :language %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admined_page1s/edit.html.erb
<h1>Editing admined_page1</h1>

<%= render 'form' %>

<%= link_to 'Show', @admined_page1 %> |
<%= link_to 'Back', admined_page1s_path %>

<div id="log_out_link_id">
  <%= link_to "Log out", log_out_path %>
</div>

app/views/admined_page1s/index.html.erb
<h1>Listing admined_page1s</h1>

<div id="log_out_link_id">
  <%= link_to "Log out", log_out_path %>
</div>

<table>
  <tr>
    <th>P1</th>
    <th>P2</th>
    <th>P3</th>
    <th>Language</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admined_page1s.each do |admined_page1| %>
  <tr>
    <td><%= admined_page1.p1 %></td>
    <td><%= admined_page1.p2 %></td>
    <td><%= admined_page1.p3 %></td>
    <td><%= admined_page1.language %></td>
    <td><%= link_to 'Show', admined_page1 %></td>
    <td><%= link_to 'Edit', edit_admined_page1_path(admined_page1) %></td>
    <td><%= link_to 'Destroy', admined_page1, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Admined page1', new_admined_page1_path %>

app/views/admined_page1s/new.html.erb
<h1>New admined_page1</h1>

<div id="log_out_link_id">
  <%= link_to "Log out", log_out_path %>
</div>


<%= render 'form' %>

<%= link_to 'Back', admined_page1s_path %>

app/views/admined_page1s/show.html.erb
<p id="notice"><%= notice %></p>

<div id="log_out_link_id">
  <%= link_to "Log out", log_out_path %>
</div>


<p>
  <b>P1:</b>
  <%= @admined_page1.p1 %>
</p>

<p>
  <b>P2:</b>
  <%= @admined_page1.p2 %>
</p>

<p>
  <b>P3:</b>
  <%= @admined_page1.p3 %>
</p>

<p>
  <b>Language:</b>
  <%= @admined_page1.language %>
</p>


<%= link_to 'Edit', edit_admined_page1_path(@admined_page1) %> |
<%= link_to 'Back', admined_page1s_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>PhoenixStr. | <%= @title %></title>
    <%= favicon_link_tag @favicon_img %>
    <%= stylesheet_link_tag    "application", :media => "screen"   %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
    
  <body id="<%=@bodyID%>">

    <div id="header">

      <%= image_tag(@logo_img,   :alt => t('error_messages.err_msg01'), :class => "logo_img") %>
      <%= image_tag(@header_img, :alt => t('error_messages.err_msg02'), :class => "header_img") %>
      <p>
          <%= @full_name    %> <br/>
          <%= t('.job_title_p1') %> <br/> &amp
          <%= t('.job_title_p2') %>
      </p>

      <div id="banner">
        <%= form_tag store_path, class: 'locale' do %>
          <%= select_tag 'set_locale',
            options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'this.form.submit()' %>
          <%= submit_tag 'submit' %>
          <%= javascript_tag "$('.locale input').hide()" %>
        <% end %>
      </div>

    </div> <!-- header -->


<div id="centeredmenu">
   <ul>
      <li class = "page1"><a <%= link_to t('.tab1'), @page1_tab_link %></a></li>
      <li class = "page2"><a <%= link_to t('.tab2'), @page2_tab_link %></a></li>
      <li class = "page3"><a <%= link_to t('.tab3'), @page3_tab_link %></a></li>
      <li class = "page4"><a <%= link_to t('.tab4'), @page4_tab_link %></a></li>

   </ul>
</div>

    <!-- ================================ -->
    <div class="colmask leftmenu">
      <div class="colleft">
        <div class="col1">
          <!-- Column 1 start -->
          <!--<p>From DataBase == <%=  @para1 %> </p>-->
          <%= yield %>
          <!-- Column 1 end -->
        </div> <!-- class "col1" -->

        <div class="col2">
          <!-- Column 2 start -->
          <%= image_tag(@wallpaper_img, :alt => t('error_messages.err_msg03'), :class => "wallpaper_img") %>
          <!-- Column 2 end -->
        </div> <!-- class = "col2" -->
      </div> <!-- class = "colleft" -->
    </div> <!-- class = "colmask leftmenu" -->





    <!-- ================================ --> 


    <div id="footer">
      <p> <%= @full_name    %>
          <%= t('.job_title_p1') %> &amp
          <%= t('.job_title_p2') %>
          <%= @address      %>
          <%= @phone_number %>
          <%= @fax_number   %>
      </p> 
    </div>

</body>
</html>

app/views/page/page1.html.erb
<h1><%= t('yield_page1.h1_ex1') %> </h1>
<h2><%= t('yield_page1.h2_ex1') %> </h2>
<h3><%= t('yield_page1.h3_ex1') %> </h3>

<h1><%= t('yield_page1.h1_ex1') %> </h1>
<p><%= t('yield_page1.p_ex1') %> </p>

<h2><%= t('yield_page1.h1_ex1') %> </h2>
<p><%= t('yield_page1.p_ex1') %> </p>

<h3><%= t('yield_page1.h1_ex1') %> </h3>
<p><%= t('yield_page1.p_ex1') %> </p>

<h1><%= t('yield_page1.h1_ex1') %> </h1>
<p><%= t('yield_page1.p_ex2') %> </p>
<p><%= t('yield_page1.p_ex2') %> </p>
<p><%= t('yield_page1.p_ex2') %> </p>


<% @admined_page1s.each do |admined_page1| %>
  <h3><%= admined_page1.p1%></h3>
<% end %>

app/views/page/page2.html.erb
<%= image_tag(@welcome_img,    :alt => t('error_messages.err_msg01'), :class => "info_img") %>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<p><%= t('yield_page2.t1') %> </p>
<p><%= t('yield_page2.t2') %> </p>
<p><%= t('yield_page2.t3') %> </p>
<p><%= t('yield_page2.t4') %> </p>
<p><%= t('yield_page2.t5') %> </p>
<p><%= t('yield_page2.t6') %> </p>
<p><%= t('yield_page2.t7') %> </p>
<p><%= t('yield_page2.t8') %> </p>
<%= image_tag(@signature_img,  :alt => t('error_messages.err_msg01'), :class => "infi_img") %>
<h2><%= t('yield_page2.t9') %> </h2>
<h2><%= @full_name %></h2>

app/views/page/page3.html.erb
<h1>Page 3</h1>
<p>
page 3
</p>

app/views/page/page4.html.erb
<h1>Page 4</h1>
<p>
page 4 
</p>